[package]
name = "nn_burn"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.9"
itertools = "0.12.1"
macroquad = "0.4.5"

[dependencies.burn]
version = "0.12.1"
features = [
    "train", 
    "ndarray", 
    "fusion", 
    "tch", 
    "wgpu", 
    "cuda",
    "tui",
    "metrics",
]
